steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'docker-build'
  args:
    - build
    - -f
    - Dockerfile.flutter
    - -t
    - gcr.io/studio-3328096157-e3f79/empire-web:${_TAG}
    - .
images:
  - gcr.io/studio-3328096157-e3f79/empire-web:${_TAG}
substitutions:
  _TAG: latest
