const fs = require('fs');
const path = require('path');

const COLORS = { reset: "\x1b[0m", green: "\x1b[32m", yellow: "\x1b[33m", cyan: "\x1b[36m" };
const ROOT = process.cwd();
const APP_DIR = path.join(ROOT, 'app');
const LOCALE = '[locale]'; // We assume dynamic locale routing

const STRUCTURE = [
  // 1. Root Landing
  { path: `${LOCALE}`, file: 'page.tsx', name: 'Landing Page' },
  
  // 2. Auth Group
  { path: `${LOCALE}/(auth)/login`, file: 'page.tsx', name: 'Login Page' },
  { path: `${LOCALE}/(auth)/register`, file: 'page.tsx', name: 'Register Page' },

  // 3. Protected Group - Redirector
  { path: `${LOCALE}/(protected)/dashboard`, file: 'page.tsx', name: 'Role Redirector' },

  // 4. Protected Group - Role Dashboards
  { path: `${LOCALE}/(protected)/learner`, file: 'page.tsx', name: 'Learner Dashboard' },
  { path: `${LOCALE}/(protected)/educator`, file: 'page.tsx', name: 'Educator Dashboard' },
  { path: `${LOCALE}/(protected)/parent`, file: 'page.tsx', name: 'Parent Dashboard' },
  { path: `${LOCALE}/(protected)/site`, file: 'page.tsx', name: 'Site Lead Dashboard' },
  { path: `${LOCALE}/(protected)/partner`, file: 'page.tsx', name: 'Partner Dashboard' },
  { path: `${LOCALE}/(protected)/hq`, file: 'page.tsx', name: 'HQ Dashboard' },
];

function createPlaceholder(name) {
  return `'use client';

export default function ${name.replace(/\s/g, '')}() {
  return (
    <div className="p-8">
      <h1 className="text-2xl font-bold">${name}</h1>
      <p className="mt-4 text-gray-600">Placeholder generated by scaffold script.</p>
    </div>
  );
}
`;
}

function scaffold() {
  console.log(`${COLORS.cyan}=== Scaffolding App Routing Structure ===${COLORS.reset}\n`);

  if (!fs.existsSync(APP_DIR)) {
    console.log(`${COLORS.yellow}Creating app directory...${COLORS.reset}`);
    fs.mkdirSync(APP_DIR);
  }

  STRUCTURE.forEach(route => {
    const dirPath = path.join(APP_DIR, route.path);
    const filePath = path.join(dirPath, route.file);

    // Create directory
    if (!fs.existsSync(dirPath)) {
      fs.mkdirSync(dirPath, { recursive: true });
    }

    // Create file if missing
    if (!fs.existsSync(filePath)) {
      console.log(`${COLORS.green}Creating: ${route.path}/${route.file}${COLORS.reset}`);
      fs.writeFileSync(filePath, createPlaceholder(route.name));
    } else {
      console.log(`Exists:   ${route.path}/${route.file}`);
    }
  });

  console.log(`\n${COLORS.cyan}=== Check for Duplicates ===${COLORS.reset}`);
  // Check for common duplicates mentioned in Audit
  const legacyLogin = path.join(APP_DIR, LOCALE, 'login');
  if (fs.existsSync(legacyLogin)) {
    console.log(`${COLORS.yellow}WARNING: Found duplicate login at 'app/${LOCALE}/login'. Move content to 'app/${LOCALE}/(auth)/login' and delete the folder.${COLORS.reset}`);
  }
  
  const rootPage = path.join(ROOT, 'page.tsx');
  if (fs.existsSync(rootPage)) {
    console.log(`${COLORS.yellow}WARNING: Found 'page.tsx' in project root. Move this to 'app/${LOCALE}/(protected)/site/page.tsx' (if it is the Site Dashboard) or 'app/${LOCALE}/page.tsx'.${COLORS.reset}`);
  }

  console.log(`\n${COLORS.green}Scaffolding complete. Run 'npm run dev' to test routes.${COLORS.reset}`);
}

scaffold();