/**
 * Analytics & Intelligence Examples
 * 
 * Demonstrates how to use the analytics system with Scholesa internal AI inference
 */

import {
  trackUnifiedEvent,
  getClassInsights,
  getLearnerProfile,
  generatePersonalizedRecommendations,
  detectLearningPatterns,
  type MissionLevel,
  type AIMode
} from '@/src/lib/analytics';
import { Timestamp } from 'firebase/firestore';

// ==================== EXAMPLE 1: Track Mission Selection ====================

export async function trackMissionSelection(
  userId: string,
  siteId: string,
  missionId: string,
  level: MissionLevel,
  grade: number
) {
  await trackUnifiedEvent({
    userId,
    userRole: 'learner',
    siteId,
    grade,
    telemetryEvent: 'mission_selected',
    analyticsEvent: {
      event_name: 'mission_selected',
      event_id: `ms_${Date.now()}`,
      event_time: Timestamp.now(),
      class_id: siteId,
      student_id: userId,
      grade_band_id: grade <= 3 ? 'grades_1_3' : grade <= 6 ? 'grades_4_6' : 'grades_7_9',
      app_version: '1.0.0',
      device_type: 'web',
      source_screen: 'mission_browser',
      mission_id: missionId,
      level
    },
    metadata: {
      missionId,
      level,
      timestamp: new Date().toISOString()
    }
  });
}

// ==================== EXAMPLE 2: Track Checkpoint Submission ====================

export async function trackCheckpointSubmission(
  userId: string,
  siteId: string,
  checkpointId: string,
  missionId: string,
  skillId: string,
  passed: boolean,
  attemptNo: number,
  grade: number
) {
  await trackUnifiedEvent({
    userId,
    userRole: 'learner',
    siteId,
    grade,
    telemetryEvent: passed ? 'checkpoint_passed' : 'checkpoint_failed',
    analyticsEvent: {
      event_name: 'checkpoint_submitted',
      event_id: `cp_${Date.now()}`,
      event_time: Timestamp.now(),
      class_id: siteId,
      student_id: userId,
      grade_band_id: grade <= 3 ? 'grades_1_3' : grade <= 6 ? 'grades_4_6' : 'grades_7_9',
      app_version: '1.0.0',
      device_type: 'web',
      source_screen: 'checkpoint',
      checkpoint_id: checkpointId,
      mission_id: missionId,
      skill_id: skillId,
      attempt_no: attemptNo,
      passed
    },
    metadata: {
      checkpointId,
      passed,
      attemptNo
    }
  });
}

// ==================== EXAMPLE 3: Track AI Coach Usage ====================

export async function trackAICoachUsage(
  userId: string,
  siteId: string,
  interactionId: string,
  mode: AIMode,
  turns: number,
  missionId: string,
  grade: number
) {
  await trackUnifiedEvent({
    userId,
    userRole: 'learner',
    siteId,
    grade,
    telemetryEvent: 'ai_hint_requested',
    analyticsEvent: {
      event_name: 'ai_coach_used',
      event_id: `ai_${Date.now()}`,
      event_time: Timestamp.now(),
      class_id: siteId,
      student_id: userId,
      grade_band_id: grade <= 3 ? 'grades_1_3' : grade <= 6 ? 'grades_4_6' : 'grades_7_9',
      app_version: '1.0.0',
      device_type: 'web',
      source_screen: 'ai_coach',
      interaction_id: interactionId,
      mode,
      turns,
      mission_id: missionId
    },
    metadata: {
      interactionId,
      mode,
      turns
    }
  });
}

// ==================== EXAMPLE 4: Get Class Insights with AI ====================

export async function getTeacherDashboardInsights(classId: string, sessionId?: string) {
  // This uses Scholesa internal AI inference to generate AI-powered insights
  const insights = await getClassInsights(classId, sessionId);
  
  console.log('Class Metrics:', insights.metrics);
  console.log('AI-Powered Insights:', insights.insights);
  
  return insights;
}

// Example output:
// {
//   classId: "class_123",
//   metrics: {
//     checkpointPassRate: 0.73,
//     attemptsToMastery: 2.1,
//     hintDependencyIndex: 2.3,
//     explainItBackCompliance: 0.65
//   },
//   insights: [
//     {
//       id: "encourage_peer_support",
//       recommendation: "Students with high hint dependency would benefit from peer pairing",
//       actions: ["create_mixed_ability_crews", "enable_peer_teaching_protocols"],
//       priority: "medium",
//       category: "collaboration",
//       triggered: true
//     }
//   ]
// }

// ==================== EXAMPLE 5: Get Personalized Learner Recommendations ====================

export async function getStudentRecommendations(userId: string, siteId: string) {
  const recommendations = await generatePersonalizedRecommendations(
    userId,
    siteId,
    {
      recentActivities: [
        'Completed Bronze mission on geometry',
        'Attempted Silver checkpoint (failed twice)',
        'Used AI coach 4 times',
        'Submitted reflection on learning'
      ],
      currentMission: 'Build a scale model',
      strugglingConcepts: ['ratios', 'proportional reasoning']
    }
  );
  
  console.log('Recommendations:', recommendations);
  
  return recommendations;
}

// Example output (generated by Scholesa internal AI):
// {
//   recommendations: [
//     "Try a Bridge mission on ratios before tackling the Silver level",
//     "Watch the exemplar video showing proportion calculations",
//     "Partner with a peer who has mastered this concept"
//   ],
//   nextSteps: [
//     "Complete the ratio practice checkpoint",
//     "Explain your thinking out loud (explain-it-back)"
//   ],
//   encouragement: "I see you're working hard on proportions! Your persistence is impressive. Let's build on what you know about geometry to make ratios click."
// }

// ==================== EXAMPLE 6: Detect Learning Patterns ====================

export async function analyzeLearnerPatterns(userId: string, siteId: string) {
  const patterns = await detectLearningPatterns(userId, siteId, 'week');
  
  console.log('Detected Patterns:', patterns);
  
  return patterns;
}

// Example output (generated by Scholesa internal AI):
// {
//   patterns: [
//     {
//       pattern: "Quick starter, gradual finisher",
//       confidence: 0.82,
//       description: "Student consistently chooses challenging missions but takes multiple attempts to complete checkpoints. Shows persistence and growth mindset."
//     },
//     {
//       pattern: "AI-assisted learner",
//       confidence: 0.75,
//       description: "Frequently uses AI coach for hints before attempting checkpoints. Could benefit from more independent problem-solving opportunities."
//     }
//   ],
//   strengths: [
//     "Strong autonomy - consistently selects GOLD missions",
//     "Excellent reflection practice - submits thoughtful reflections",
//     "Good collaboration - actively gives peer feedback"
//   ],
//   growthAreas: [
//     "Reduce AI dependency by attempting checkpoints before requesting hints",
//     "Build competence confidence through more Bronze/Silver completions"
//   ]
// }

// ==================== EXAMPLE 7: Get Learner Profile (SDT Scores) ====================

export async function getStudentMotivationProfile(userId: string, siteId: string) {
  const profile = await getLearnerProfile(userId, siteId);
  
  console.log('SDT Motivation Profile:', profile.sdtScores);
  console.log('Engagement Score:', profile.engagementScore);
  
  return profile;
}

// Example output:
// {
//   userId: "learner_456",
//   siteId: "site_789",
//   sdtScores: {
//     autonomy: 78,  // High choice-making and agency
//     competence: 62, // Moderate skill mastery
//     belonging: 85   // Strong social connection
//   },
//   engagementScore: 72,
//   insights: [],
//   lastUpdated: "2026-01-17T10:30:00Z"
// }
