#!/usr/bin/env node
/**
 * Scholesa Icon Generator
 *
 * Canonical source-of-truth: repo-root scholesa.svg.
 * This helper only resizes the derived launcher PNG that is regenerated by
 * scripts/sync_platform_icons.sh and convert_brand_assets.py.
 * Run: node generate-icons.js
 *
 * Prerequisites:
 *   npm install sharp
 */

const fs = require('fs');
const path = require('path');
const cp = require('child_process');

async function generateIcons() {
  const canonicalSvgPath = path.join(__dirname, '..', '..', '..', '..', 'scholesa.svg');
  const derivedLauncherPngPath = path.join(__dirname, '..', 'assets', 'icons', 'scholesa_launcher.png');
  const iconsDir = path.join(__dirname, 'icons');

  if (!fs.existsSync(derivedLauncherPngPath)) {
    throw new Error(
      `Derived launcher PNG not found: ${derivedLauncherPngPath}. ` +
      `Regenerate assets from canonical SVG source first: ${canonicalSvgPath}`
    );
  }
  
  const sizes = [
    { name: 'favicon-16x16.png', size: 16 },
    { name: 'favicon-32x32.png', size: 32 },
    { name: 'Icon-192.png', size: 192 },
    { name: 'Icon-512.png', size: 512 },
    { name: 'Icon-maskable-192.png', size: 192 },
    { name: 'Icon-maskable-512.png', size: 512 },
  ];

  try {
    const sharp = require('sharp');
    const sourceBuffer = fs.readFileSync(derivedLauncherPngPath);
    
    for (const { name, size } of sizes) {
      const outputPath = path.join(iconsDir, name);
      const isMaskable = name.includes('maskable');
      const padding = isMaskable ? Math.floor(size * 0.1) : 0;
      const innerSize = size - (padding * 2);
      
      let buffer;
      if (isMaskable) {
        buffer = await sharp(sourceBuffer)
          .resize(innerSize, innerSize)
          .extend({
            top: padding,
            bottom: padding,
            left: padding,
            right: padding,
            background: { r: 0, g: 0, b: 0, alpha: 0 }
          })
          .png()
          .toBuffer();
      } else {
        buffer = await sharp(sourceBuffer)
          .resize(size, size)
          .png()
          .toBuffer();
      }
      
      fs.writeFileSync(outputPath, buffer);
      console.log(`✓ Generated ${name} (${size}x${size})`);
    }
    
    const faviconPngPath = path.join(iconsDir, 'favicon-32x32.png');
    cp.execFileSync('sips', ['-s', 'format', 'ico', faviconPngPath, '--out', path.join(iconsDir, 'favicon.ico')], {
      stdio: 'pipe',
    });
    console.log('✓ Generated favicon.ico');
    
    console.log('\n✅ All icons generated successfully!');
    
  } catch (err) {
    if (err.code === 'MODULE_NOT_FOUND') {
      console.log('Sharp not installed.');
      console.log('\nTo generate PNG icons:');
      console.log('  1. Refresh derived assets from canonical scholesa.svg');
      console.log('     bash ../scripts/sync_platform_icons.sh');
      console.log('  2. npm install sharp && node generate-icons.js');
      console.log('\nOr open generate-icons.html in browser.\n');
    } else {
      throw err;
    }
  }
}

generateIcons().catch(console.error);
