platform :osx, '10.15'
inhibit_all_warnings!

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'ephemeral', 'Flutter-Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure \"flutter pub get\" is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Flutter-Generated.xcconfig, then run \"flutter pub get\""
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_macos_podfile_setup

target 'Runner' do
  use_frameworks!

  flutter_install_all_macos_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_macos_build_settings(target)
    target.build_configurations.each do |config|
      if config.build_settings['MACOSX_DEPLOYMENT_TARGET'].to_f < 11.0
        config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '11.0'
      end
      other_ldflags = config.build_settings['OTHER_LDFLAGS'] || '$(inherited)'
      unless other_ldflags.include?('-Wl,-no_warn_duplicate_libraries')
        config.build_settings['OTHER_LDFLAGS'] = "#{other_ldflags} -Wl,-no_warn_duplicate_libraries".strip
      end
    end

    target.shell_script_build_phases.each do |phase|
      next unless phase.name == 'Create Symlinks to Header Folders'
      if phase.output_paths.nil? || phase.output_paths.empty?
        phase.output_paths = ["$(DERIVED_FILE_DIR)/#{target.name}_symlink_headers.stamp"]
      end
    end
  end

  installer.aggregate_targets.each do |aggregate_target|
    aggregate_target.user_project.native_targets.each do |native_target|
      native_target.shell_script_build_phases.each do |phase|
        next unless ['Flutter Assemble', 'Run Script'].include?(phase.name)
        if phase.output_paths.nil? || phase.output_paths.empty?
          phase.output_paths = ["$(DERIVED_FILE_DIR)/#{native_target.name}_#{phase.name.gsub(' ', '_').downcase}.stamp"]
        end
      end
    end
    aggregate_target.user_project.save
  end
end
