/**
 * Grade Band Policy System
 * 
 * Age-appropriate feature gating based on developmental appropriateness
 * K-3, 4-6, 7-9, 10-12
 */

import type { AgeBand } from '@/src/types/schema';

export interface GradeBandPolicy {
  // Core settings
  ageBand: AgeBand;
  minGrade: number;
  maxGrade: number;
  
  // Sprint & Mission settings
  maxSprintMinutes: number;
  minSprintMinutes: number;
  missionChoiceCount: 2 | 3;
  allowCustomMissions: boolean;
  
  // AI Coach modes
  aiCoach: {
    enabled: boolean;
    modes: {
      hint: boolean;
      rubricCheck: boolean;
      debug: boolean;
      critique: boolean;
    };
    requireTeacherGuidance: boolean;
    explainBackRequired: boolean;
  };
  
  // Social features
  social: {
    peerFeedback: {
      enabled: boolean;
      requireTemplate: boolean; // Must use "I like / I wonder / Next step"
      allowFreeform: boolean;
    };
    peerMessaging: {
      enabled: boolean;
      moderationRequired: boolean;
    };
    publicShowcase: {
      enabled: boolean;
      defaultVisibility: 'crew' | 'site' | 'private';
    };
    recognitionTokens: {
      enabled: boolean;
      types: string[]; // Which recognition types are shown
    };
  };
  
  // Reflection settings
  reflection: {
    promptCount: 1 | 2 | 3 | 4;
    emojiScalesEnabled: boolean;
    strategyPromptEnabled: boolean;
    evidenceLinkingEnabled: boolean; // Can link to specific artifacts
  };
  
  // Rubric complexity
  rubric: {
    levelCount: 2 | 3 | 4; // "I can..." vs 3-level vs detailed
    showExemplars: boolean;
    allowResubmission: boolean;
    studentFacingLanguage: 'simple' | 'standard' | 'detailed';
  };
  
  // Portfolio settings
  portfolio: {
    studentOwned: boolean;
    visibility: {
      student: boolean;
      parent: boolean;
      public: boolean;
      exportable: boolean;
    };
    autoGenerated: boolean;
    allowCustomization: boolean;
  };
  
  // Gamification
  gamification: {
    badges: 'stickers' | 'standard' | 'professional';
    showStreaks: boolean;
    showProgressBars: boolean;
    publicLeaderboards: boolean; // Always false per requirements
  };
  
  // UI/UX preferences
  ui: {
    iconOverText: boolean; // Big buttons with icons vs text-heavy
    audioFeedback: boolean; // Teacher audio notes
    simplifiedNavigation: boolean;
  };
  
  // Safety & moderation
  safety: {
    contentModeration: 'strict' | 'standard' | 'relaxed';
    requireParentConsent: boolean;
    mentorAccess: boolean;
    publicProfile: boolean;
  };
}

/**
 * Grade Band Policies by age group
 */
export const GRADE_BAND_POLICIES: Record<AgeBand, GradeBandPolicy> = {
  grades_1_3: {
    ageBand: 'grades_1_3',
    minGrade: 1,
    maxGrade: 3,
    
    maxSprintMinutes: 10,
    minSprintMinutes: 5,
    missionChoiceCount: 2,
    allowCustomMissions: false,
    
    aiCoach: {
      enabled: true,
      modes: {
        hint: true,
        rubricCheck: false,
        debug: false,
        critique: false
      },
      requireTeacherGuidance: true, // Teacher must approve AI use
      explainBackRequired: false // Too young for complex explain-back
    },
    
    social: {
      peerFeedback: {
        enabled: false, // No peer feedback at this age
        requireTemplate: true,
        allowFreeform: false
      },
      peerMessaging: {
        enabled: false,
        moderationRequired: true
      },
      publicShowcase: {
        enabled: false, // Teacher-mediated only
        defaultVisibility: 'private'
      },
      recognitionTokens: {
        enabled: true,
        types: ['helper', 'courage_to_try'] // Simple recognition only
      }
    },
    
    reflection: {
      promptCount: 1,
      emojiScalesEnabled: true,
      strategyPromptEnabled: false,
      evidenceLinkingEnabled: false
    },
    
    rubric: {
      levelCount: 2, // "I can..." yes/no
      showExemplars: true,
      allowResubmission: true,
      studentFacingLanguage: 'simple'
    },
    
    portfolio: {
      studentOwned: false,
      visibility: {
        student: false,
        parent: true,
        public: false,
        exportable: false
      },
      autoGenerated: true,
      allowCustomization: false
    },
    
    gamification: {
      badges: 'stickers',
      showStreaks: true,
      showProgressBars: true,
      publicLeaderboards: false
    },
    
    ui: {
      iconOverText: true,
      audioFeedback: true,
      simplifiedNavigation: true
    },
    
    safety: {
      contentModeration: 'strict',
      requireParentConsent: true,
      mentorAccess: false,
      publicProfile: false
    }
  },
  
  grades_4_6: {
    ageBand: 'grades_4_6',
    minGrade: 4,
    maxGrade: 6,
    
    maxSprintMinutes: 30,
    minSprintMinutes: 15,
    missionChoiceCount: 3,
    allowCustomMissions: false,
    
    aiCoach: {
      enabled: true,
      modes: {
        hint: true,
        rubricCheck: false,
        debug: true, // Ask questions mode
        critique: false
      },
      requireTeacherGuidance: false,
      explainBackRequired: true
    },
    
    social: {
      peerFeedback: {
        enabled: true,
        requireTemplate: true, // Must use structured format
        allowFreeform: false
      },
      peerMessaging: {
        enabled: false,
        moderationRequired: true
      },
      publicShowcase: {
        enabled: true,
        defaultVisibility: 'crew'
      },
      recognitionTokens: {
        enabled: true,
        types: ['helper', 'debugger', 'clear_communicator', 'courage_to_try']
      }
    },
    
    reflection: {
      promptCount: 2,
      emojiScalesEnabled: true,
      strategyPromptEnabled: true,
      evidenceLinkingEnabled: false
    },
    
    rubric: {
      levelCount: 3, // Emerging / Developing / Proficient
      showExemplars: true,
      allowResubmission: true,
      studentFacingLanguage: 'standard'
    },
    
    portfolio: {
      studentOwned: false,
      visibility: {
        student: true,
        parent: true,
        public: false,
        exportable: false
      },
      autoGenerated: true,
      allowCustomization: true // Can add titles/captions
    },
    
    gamification: {
      badges: 'standard',
      showStreaks: true,
      showProgressBars: true,
      publicLeaderboards: false
    },
    
    ui: {
      iconOverText: false,
      audioFeedback: true,
      simplifiedNavigation: false
    },
    
    safety: {
      contentModeration: 'standard',
      requireParentConsent: true,
      mentorAccess: false,
      publicProfile: false
    }
  },
  
  grades_7_9: {
    ageBand: 'grades_7_9',
    minGrade: 7,
    maxGrade: 9,
    
    maxSprintMinutes: 45,
    minSprintMinutes: 20,
    missionChoiceCount: 3,
    allowCustomMissions: true,
    
    aiCoach: {
      enabled: true,
      modes: {
        hint: true,
        rubricCheck: true,
        debug: true,
        critique: false // Not full critique yet
      },
      requireTeacherGuidance: false,
      explainBackRequired: true
    },
    
    social: {
      peerFeedback: {
        enabled: true,
        requireTemplate: true,
        allowFreeform: false // Still structured
      },
      peerMessaging: {
        enabled: false, // No open DMs
        moderationRequired: true
      },
      publicShowcase: {
        enabled: true,
        defaultVisibility: 'site'
      },
      recognitionTokens: {
        enabled: true,
        types: ['helper', 'debugger', 'clear_communicator', 'courage_to_try']
      }
    },
    
    reflection: {
      promptCount: 3,
      emojiScalesEnabled: true,
      strategyPromptEnabled: true,
      evidenceLinkingEnabled: true
    },
    
    rubric: {
      levelCount: 3,
      showExemplars: true,
      allowResubmission: true,
      studentFacingLanguage: 'detailed'
    },
    
    portfolio: {
      studentOwned: true,
      visibility: {
        student: true,
        parent: true,
        public: false,
        exportable: false
      },
      autoGenerated: false,
      allowCustomization: true
    },
    
    gamification: {
      badges: 'standard',
      showStreaks: true,
      showProgressBars: true,
      publicLeaderboards: false
    },
    
    ui: {
      iconOverText: false,
      audioFeedback: false,
      simplifiedNavigation: false
    },
    
    safety: {
      contentModeration: 'standard',
      requireParentConsent: false,
      mentorAccess: true, // Moderated Q&A
      publicProfile: false
    }
  },
  
  grades_10_12: {
    ageBand: 'grades_10_12',
    minGrade: 10,
    maxGrade: 12,
    
    maxSprintMinutes: 90,
    minSprintMinutes: 30,
    missionChoiceCount: 3,
    allowCustomMissions: true,
    
    aiCoach: {
      enabled: true,
      modes: {
        hint: true,
        rubricCheck: true,
        debug: true,
        critique: true // Full AI critique
      },
      requireTeacherGuidance: false,
      explainBackRequired: true
    },
    
    social: {
      peerFeedback: {
        enabled: true,
        requireTemplate: false, // Can write freely
        allowFreeform: true
      },
      peerMessaging: {
        enabled: false, // Still no open DMs (safety)
        moderationRequired: true
      },
      publicShowcase: {
        enabled: true,
        defaultVisibility: 'site'
      },
      recognitionTokens: {
        enabled: true,
        types: ['helper', 'debugger', 'clear_communicator', 'courage_to_try']
      }
    },
    
    reflection: {
      promptCount: 4,
      emojiScalesEnabled: false, // Too childish
      strategyPromptEnabled: true,
      evidenceLinkingEnabled: true
    },
    
    rubric: {
      levelCount: 4, // Detailed rubric
      showExemplars: true,
      allowResubmission: true,
      studentFacingLanguage: 'detailed'
    },
    
    portfolio: {
      studentOwned: true,
      visibility: {
        student: true,
        parent: true,
        public: true, // Can share publicly
        exportable: true // For college/job applications
      },
      autoGenerated: false,
      allowCustomization: true
    },
    
    gamification: {
      badges: 'professional',
      showStreaks: false, // Less gamified
      showProgressBars: true,
      publicLeaderboards: false
    },
    
    ui: {
      iconOverText: false,
      audioFeedback: false,
      simplifiedNavigation: false
    },
    
    safety: {
      contentModeration: 'relaxed',
      requireParentConsent: false,
      mentorAccess: true,
      publicProfile: true
    }
  }
};

/**
 * Get policy for a learner based on their grade
 */
export function getPolicyForGrade(grade: number): GradeBandPolicy {
  if (grade >= 1 && grade <= 3) return GRADE_BAND_POLICIES.grades_1_3;
  if (grade >= 4 && grade <= 6) return GRADE_BAND_POLICIES.grades_4_6;
  if (grade >= 7 && grade <= 9) return GRADE_BAND_POLICIES.grades_7_9;
  if (grade >= 10 && grade <= 12) return GRADE_BAND_POLICIES.grades_10_12;
  
  // Default to middle school
  return GRADE_BAND_POLICIES.grades_7_9;
}

/**
 * Get age band from grade
 */
export function getAgeBandFromGrade(grade: number): AgeBand {
  if (grade >= 1 && grade <= 3) return 'grades_1_3';
  if (grade >= 4 && grade <= 6) return 'grades_4_6';
  if (grade >= 7 && grade <= 9) return 'grades_7_9';
  return 'grades_10_12';
}

/**
 * Check if feature is available for grade
 */
export function isFeatureAvailable(
  grade: number,
  feature: keyof GradeBandPolicy
): boolean {
  const policy = getPolicyForGrade(grade);
  return !!policy[feature];
}

/**
 * Get AI Coach modes for grade
 */
export function getAICoachModesForGrade(grade: number): Array<'hint' | 'rubric_check' | 'debug' | 'critique'> {
  const policy = getPolicyForGrade(grade);
  const modes: Array<'hint' | 'rubric_check' | 'debug' | 'critique'> = [];
  
  if (policy.aiCoach.modes.hint) modes.push('hint');
  if (policy.aiCoach.modes.rubricCheck) modes.push('rubric_check');
  if (policy.aiCoach.modes.debug) modes.push('debug');
  if (policy.aiCoach.modes.critique) modes.push('critique');
  
  return modes;
}
