extend type Query {
  """
  ✨ Look up a single `Attendance` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  attendance(
    """
    The key used to identify the object.
    """
    key: Attendance_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Attendance_FirstRow
  ): Attendance @fdc_generated(from: "Attendance", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Event` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  event(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Event_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Event_FirstRow
  ): Event @fdc_generated(from: "Event", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `PerformanceStat` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  performanceStat(
    """
    The key used to identify the object.
    """
    key: PerformanceStat_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PerformanceStat_FirstRow
  ): PerformanceStat @fdc_generated(from: "PerformanceStat", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Player` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  player(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Player_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Player_FirstRow
  ): Player @fdc_generated(from: "Player", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Team` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  team(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Team_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Team_FirstRow
  ): Team @fdc_generated(from: "Team", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ List `Attendance` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  attendances(
    """
    Filter condition to narrow down the query results.
    """
    where: Attendance_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Attendance_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Attendance_Having
  ): [Attendance!]! @fdc_generated(from: "Attendance", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Event` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  events(
    """
    Filter condition to narrow down the query results.
    """
    where: Event_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Event_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Event_Having
  ): [Event!]! @fdc_generated(from: "Event", purpose: QUERY_MULTIPLE)
  """
  ✨ List `PerformanceStat` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  performanceStats(
    """
    Filter condition to narrow down the query results.
    """
    where: PerformanceStat_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [PerformanceStat_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: PerformanceStat_Having
  ): [PerformanceStat!]! @fdc_generated(from: "PerformanceStat", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Player` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  players(
    """
    Filter condition to narrow down the query results.
    """
    where: Player_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Player_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Player_Having
  ): [Player!]! @fdc_generated(from: "Player", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Team` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  teams(
    """
    Filter condition to narrow down the query results.
    """
    where: Team_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Team_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Team_Having
  ): [Team!]! @fdc_generated(from: "Team", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
}
