#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
COMMAND="${1:-verify}"
TIMESTAMP="$(date -u +%Y%m%dT%H%M%SZ)"
PROOF_DIR="${NATIVE_DISTRIBUTION_PROOF_DIR:-$REPO_ROOT/docs/native-distribution-proof-$TIMESTAMP}"
PROOF_DOC="$PROOF_DIR/README.md"
CONFIRM_VALUE="I_UNDERSTAND_THIS_UPLOADS_NATIVE_BUILDS"

fail() {
  echo "[native-proof] $*" >&2
  exit 1
}

run_and_capture() {
  local label="$1"
  local command="$2"
  local log_file="$3"

  echo "[native-proof] Running $label..."
  if (cd "$REPO_ROOT" && eval "$command") > "$log_file" 2>&1; then
    echo "[native-proof] PASS $label"
  else
    echo "[native-proof] FAIL $label"
    tail -120 "$log_file" >&2 || true
    return 1
  fi
}

write_proof_doc() {
  cat > "$PROOF_DOC" <<EOF
# Native Distribution Proof - $TIMESTAMP

This proof was generated by \`./scripts/native_distribution_proof.sh execute-live\`.

## Commands

- iOS TestFlight: \`./scripts/apple_release_local.sh upload_testflight\`
- Android Play internal: \`./scripts/android_release_local.sh upload_internal\`
- macOS build: \`./scripts/deploy.sh flutter-macos\`
- macOS notarization: \`./scripts/macos_release_local.sh sign_notarize_staple\`

## Logs

- iOS: \`ios-testflight.log\`
- Android: \`android-play-internal.log\`
- macOS build: \`macos-build.log\`
- macOS notarization: \`macos-notarization.log\`

## Operator Decision

Native-channel Gold still requires a release owner to verify the TestFlight build, Google Play internal release, and notarized/stapled macOS app in the relevant Apple/Google distribution consoles before including native-channel scope in Blanket Gold.
EOF
}

case "$COMMAND" in
  verify)
    "$REPO_ROOT/scripts/native_distribution_readiness.sh"
    ;;
  execute-live)
    [[ "${SCHOLESA_NATIVE_DISTRIBUTION_CONFIRM:-}" == "$CONFIRM_VALUE" ]] \
      || fail "Set SCHOLESA_NATIVE_DISTRIBUTION_CONFIRM=$CONFIRM_VALUE to run live TestFlight, Google Play, and macOS notarization proof."

    "$REPO_ROOT/scripts/native_distribution_readiness.sh"
    mkdir -p "$PROOF_DIR"

    run_and_capture "iOS TestFlight upload" "./scripts/apple_release_local.sh upload_testflight" "$PROOF_DIR/ios-testflight.log"
    run_and_capture "Android Play internal upload" "./scripts/android_release_local.sh upload_internal" "$PROOF_DIR/android-play-internal.log"
    run_and_capture "macOS release build" "./scripts/deploy.sh flutter-macos" "$PROOF_DIR/macos-build.log"
    run_and_capture "macOS Developer ID notarization" "./scripts/macos_release_local.sh sign_notarize_staple" "$PROOF_DIR/macos-notarization.log"
    write_proof_doc

    echo "[native-proof] Native distribution proof logs written to $PROOF_DIR"
    echo "[native-proof] Proof document: $PROOF_DOC"
    ;;
  *)
    fail "Unknown command: $COMMAND. Supported commands: verify, execute-live."
    ;;
esac
