import 'package:flutter/widgets.dart';

class AppStrings {
  AppStrings._();

  static const Map<String, Map<String, String>> _localized =
      <String, Map<String, String>>{
    'en': <String, String>{
      'auth.welcomeBack': 'Welcome back',
      'auth.welcomeToScholesa': 'Welcome to Scholesa',
      'auth.signInSubtitle': 'Sign in to continue your learning journey',
      'auth.email': 'Email',
      'auth.password': 'Password',
      'auth.emailHint': 'you@example.com',
      'auth.passwordHint': '••••••••',
      'auth.forgotPassword': 'Forgot password?',
      'auth.signIn': 'Sign In',
      'auth.recentAccountsTitle': 'Recent accounts on this device',
      'auth.recentAccountsSubtitle':
          'Use a remembered family account to prefill email or continue with the same provider. Passwords are never stored, and only one session stays active at a time.',
      'auth.removeRememberedAccount': 'Remove',
      'auth.rememberedAccountRemoved': 'Account removed from this device.',
      'auth.useEmail': 'Use email',
      'auth.savedAccount': 'Saved account',
      'auth.orContinueWith': 'or continue with',
      'auth.google': 'Google',
      'auth.microsoft': 'Microsoft',
      'auth.provisioningNote':
          'Accounts are provisioned by your site or HQ admin.',
      'auth.resetPassword': 'Reset Password',
      'auth.resetPasswordHelp':
          'Enter your email address and we\'ll send you a link to reset your password.',
      'auth.cancel': 'Cancel',
      'auth.sendResetLink': 'Send Reset Link',
      'auth.resetEmailSent': 'Password reset email sent. Check your inbox.',
      'auth.validation.enterEmail': 'Please enter your email',
      'auth.validation.validEmail': 'Please enter a valid email',
      'auth.validation.enterPassword': 'Please enter your password',
      'auth.validation.passwordLength':
          'Password must be at least 6 characters',
      'auth.error.userNotFound': 'No account found with this email',
      'auth.error.wrongPassword': 'Incorrect password',
      'auth.error.invalidCredential': 'Invalid email or password',
      'auth.error.emailInUse': 'An account already exists with this email',
      'auth.error.weakPassword': 'Password is too weak',
      'auth.error.invalidEmail': 'Invalid email address',
      'auth.error.userDisabled': 'This account has been disabled',
      'auth.error.tooManyRequests': 'Too many attempts. Please try again later',
      'auth.error.networkFailed':
          'Network error. Check your connection and try again',
      'auth.error.operationNotAllowed': 'Email/password sign-in is not enabled',
      'auth.error.invalidApiKey':
          'Authentication is misconfigured. Contact support',
      'auth.error.appNotAuthorized':
          'This app is not authorized for Firebase Auth',
      'auth.error.popupClosed': 'Sign-in popup was closed before completion',
      'auth.error.popupBlocked': 'Sign-in popup was blocked by your browser',
      'auth.error.googleFailed': 'Failed to sign in with Google',
      'auth.error.microsoftFailed': 'Failed to sign in with Microsoft',
      'auth.error.signOutFailed':
          'We could not sign you out right now. Please try again.',
      'auth.error.profileLoadFailed': 'Failed to load user profile',
      'auth.error.generic': 'Authentication failed',
      'auth.error.unexpected': 'An unexpected error occurred',
      'auth.error.resetFailed': 'Failed to send reset email',
      'app.title': 'Scholesa',
      'app.bootstrapFailed': 'Failed to start Scholesa',
      'app.recoveryModeTitle': 'Scholesa started in recovery mode',
      'app.recoveryModeBody':
          'Some startup services failed, so parts of the app may be unavailable until the next restart.',
      'app.affectedServices': 'Affected services',
      'app.retry': 'Retry',
      'app.dismiss': 'Dismiss',
      'app.startupService.localStorage': 'Local storage',
      'app.startupService.firebase': 'Firebase',
      'app.startupService.authEmulator': 'Auth emulator',
      'app.startupService.generic': 'Startup service',
        'assistant.tooltip': 'Get help',
        'assistant.title': 'Get help',
      'assistant.close': 'Close',
        'assistant.loading': 'Loading help…',
        'assistant.hoverHint': 'Click for help',
      'ai.greeting.initial':
          'Hi! I can guide you with hints, explanations, and quick debug steps whenever you need support.',
      'ai.autoAssist.hesitationPrompt':
          'The learner may be hesitating. Current support state: {state}. Offer a short supportive check-in, one tiny next step, and one follow-up question.',
      'ai.autoAssist.interventionPrompt':
          'A proactive support moment was detected. Intervention type: {type}, salience: {salience}, reason codes: {reasons}. Give a short supportive voice nudge with one immediate action and one follow-up question.',
      'ai.autoAssist.fallbackPrompt':
          'Check in proactively with the learner. Offer one tiny next step and ask a confidence-building follow-up question.',
      'ai.error.unreachable':
          'Help is not available right now. Try again in a moment.',
      'ai.error.safeEscalation':
          'I want to be careful here. Share what you have tried so far, and I can help with the next safe step. If you need a full check, ask your educator to review it with you.',
      'ai.voice.transcriptionUnavailable':
          'Voice transcription unavailable. Please type your question.',
      'ai.voice.microphonePermissionRequired':
          'Microphone permission is required for voice input.',
      'ai.voice.playbackStopped': 'Playback stopped',
      'ai.voice.stopListening': 'Stop listening',
      'ai.voice.useInput': 'Use voice input',
      'ai.voice.disableOutput': 'Disable voice output',
      'ai.voice.enableOutput': 'Enable voice output',
      'ai.voice.speaking': 'Speaking…',
      'ai.voice.tapInterrupt': 'Tap to interrupt',
      'ai.voiceOnly.promptTap':
          'Tap the mic and speak. Help will answer out loud.',
      'ai.voiceOnly.listening': 'Listening… speak now.',
      'ai.voiceOnly.answeredOutLoud':
          'Help answered out loud. Replay the spoken response if you need to hear it again.',
      'ai.voiceOnly.replay': 'Replay spoken response',
      'ai.voice.outputUnavailable':
          'Voice output is unavailable. Check device volume and audio permissions.',
      'ai.voice.outputUnavailableWeb':
          'Voice output is blocked in the browser. Use HTTPS, allow autoplay/audio, and try again.',
      'ai.clearGoals.title': 'Clear current goals?',
      'ai.clearGoals.body':
          'This removes the in-session coaching goals memory for this assistant conversation.',
      'ai.clear': 'Clear',
      'ai.currentGoals': 'Current goals',
      'ai.clearGoals.cta': 'Clear goals',
    'ai.empty.title': 'AI Help',
      'ai.empty.subtitle':
          'Choose a help mode and ask a question. I\'ll guide your thinking, not hand over the answer.',
      'ai.banner.verification':
          'Understanding check active — show your thinking first.',
      'ai.banner.runtimeUnavailable':
          'Live learning signals are unavailable right now. Confidence stays at 0% until real session evidence arrives, so coaching stays careful.',
      'ai.banner.runtimeMalformed':
          'Live learning signals could not be trusted. Confidence stays at 0% until the session state is repaired.',
      'ai.banner.learnerGuarded':
          'Confidence {percent}%. Help uses live learning signals plus a synthetic baseline, and stays careful below 97%.',
      'ai.banner.lineageDisclosure':
          'Help guidance uses live learning signals plus a synthetic baseline. The synthetic baseline helps with support, but it is not learner evidence or proof of mastery.',
      'ai.chat.verificationRequired': 'Verification required',
      'ai.chat.helpful': 'Helpful?',
      'ai.feedback.thanks': 'Thanks for the feedback!',
      'ai.feedback.noted': 'Noted — we\'ll improve.',
      'ai.enrich.retryPrompt':
          'Let\'s try that again. What part feels most confusing right now?',
      'ai.enrich.hintFollowup': 'What have you tried so far?',
      'ai.enrich.verifyFollowup': 'Can you show the evidence for your answer?',
      'ai.enrich.explainFollowup':
          'How would you explain that in your own words?',
      'ai.enrich.debugFollowup': 'What changed right before the issue started?',
      'ai.mode.hintPlaceholder': 'Ask for a hint...',
      'ai.mode.verifyPlaceholder': 'Describe your approach to verify...',
      'ai.mode.explainPlaceholder': 'What would you like explained?',
      'ai.mode.debugPlaceholder': 'Describe the issue you\'re seeing...',
      'ai.mode.hintLabel': 'Hint',
      'ai.mode.verifyLabel': 'Verify',
      'ai.mode.explainLabel': 'Explain',
      'ai.mode.debugLabel': 'Debug',
      'ai.directive.hint':
          'Give one focused hint first, then ask a short guiding question.',
      'ai.directive.verify':
          'Verify reasoning with evidence checks and ask for one concrete proof step.',
      'ai.directive.explain':
          'Explain in simple steps and relate to one practical example.',
      'ai.directive.debug':
          'Diagnose likely causes, suggest one small test, and ask what changed recently.',
      'ai.role.learner':
          'Speak directly to a learner using supportive, age-appropriate coaching language.',
      'ai.role.parent':
          'Coach with parent-friendly phrasing that supports the learner without giving answers.',
      'ai.role.staff':
          'Respond as an instructional co-pilot with concise pedagogical suggestions.',
    },
    'zh-CN': <String, String>{
      'auth.welcomeBack': '欢迎回来',
      'auth.welcomeToScholesa': '欢迎来到 Scholesa',
      'auth.signInSubtitle': '登录以继续你的学习旅程',
      'auth.email': '电子邮箱',
      'auth.password': '密码',
      'auth.emailHint': 'you@example.com',
      'auth.passwordHint': '••••••••',
      'auth.forgotPassword': '忘记密码？',
      'auth.signIn': '登录',
      'auth.recentAccountsTitle': '此设备上的最近账户',
      'auth.recentAccountsSubtitle':
          '可使用已记住的家庭账户来预填邮箱，或继续使用相同登录方式。系统不会保存密码，且同一时间只保留一个活动会话。',
      'auth.removeRememberedAccount': '移除',
      'auth.rememberedAccountRemoved': '该账户已从此设备移除。',
      'auth.useEmail': '使用邮箱',
      'auth.savedAccount': '已保存账户',
      'auth.orContinueWith': '或继续使用',
      'auth.google': 'Google',
      'auth.microsoft': 'Microsoft',
      'auth.provisioningNote': '账户由站点或 HQ 管理员预先配置。',
      'auth.resetPassword': '重置密码',
      'auth.resetPasswordHelp': '输入你的电子邮箱，我们会发送一个重置密码链接。',
      'auth.cancel': '取消',
      'auth.sendResetLink': '发送重置链接',
      'auth.resetEmailSent': '密码重置邮件已发送，请检查收件箱。',
      'auth.validation.enterEmail': '请输入电子邮箱',
      'auth.validation.validEmail': '请输入有效的电子邮箱',
      'auth.validation.enterPassword': '请输入密码',
      'auth.validation.passwordLength': '密码至少需要 6 个字符',
      'auth.error.userNotFound': '未找到此邮箱对应的账户',
      'auth.error.wrongPassword': '密码不正确',
      'auth.error.invalidCredential': '邮箱或密码无效',
      'auth.error.emailInUse': '该邮箱已存在账户',
      'auth.error.weakPassword': '密码强度过低',
      'auth.error.invalidEmail': '电子邮箱格式无效',
      'auth.error.userDisabled': '此账户已被停用',
      'auth.error.tooManyRequests': '尝试次数过多，请稍后再试',
      'auth.error.networkFailed': '网络错误，请检查连接后重试',
      'auth.error.operationNotAllowed': '当前未启用邮箱/密码登录',
      'auth.error.invalidApiKey': '认证配置有误，请联系支持团队',
      'auth.error.appNotAuthorized': '此应用未被授权使用 Firebase Auth',
      'auth.error.popupClosed': '登录弹窗在完成前已关闭',
      'auth.error.popupBlocked': '登录弹窗被浏览器拦截',
      'auth.error.googleFailed': '使用 Google 登录失败',
      'auth.error.microsoftFailed': '使用 Microsoft 登录失败',
      'auth.error.signOutFailed': '暂时无法退出登录，请重试。',
      'auth.error.profileLoadFailed': '加载用户资料失败',
      'auth.error.generic': '认证失败',
      'auth.error.unexpected': '发生了意外错误',
      'auth.error.resetFailed': '发送重置邮件失败',
      'app.title': 'Scholesa',
      'app.bootstrapFailed': 'Scholesa 启动失败',
      'app.recoveryModeTitle': 'Scholesa 以恢复模式启动',
      'app.recoveryModeBody': '部分启动服务失败，因此在下次重启前，应用的某些功能可能不可用。',
      'app.affectedServices': '受影响的服务',
      'app.retry': '重试',
      'app.dismiss': '关闭',
      'app.startupService.localStorage': '本地存储',
      'app.startupService.firebase': 'Firebase',
      'app.startupService.authEmulator': '认证模拟器',
      'app.startupService.generic': '启动服务',
    'assistant.tooltip': '获取帮助',
    'assistant.title': '获取帮助',
      'assistant.close': '关闭',
    'assistant.loading': '正在加载帮助…',
    'assistant.hoverHint': '点击获取帮助',
            'ai.greeting.initial': '你好！需要帮助时，我可以提供提示、解释和简短的调试步骤。',
      'ai.autoAssist.hesitationPrompt':
          '学习者可能正在犹豫。当前支持状态：{state}。请给出简短支持性提醒、一个微小下一步和一个追问。',
      'ai.autoAssist.interventionPrompt':
          '系统检测到一个需要主动支持的时刻。干预类型：{type}，显著性：{salience}，原因码：{reasons}。请给出简短支持性语音提醒，包含一个立即行动和一个追问。',
      'ai.autoAssist.fallbackPrompt': '请主动关心学习者，给出一个微小下一步，并提出一个增强信心的追问。',
    'ai.error.unreachable': '当前无法使用帮助，请稍后再试。',
      'ai.error.safeEscalation':
          '我想更谨慎一点。先告诉我你已经试过什么，我可以帮你想下一步更安全的做法。如果你需要完整检查，请请老师和你一起看。',
      'ai.voice.transcriptionUnavailable': '语音转写不可用，请改用文字输入。',
      'ai.voice.microphonePermissionRequired': '语音输入需要麦克风权限。',
      'ai.voice.playbackStopped': '播放已停止',
      'ai.voice.stopListening': '停止收听',
      'ai.voice.useInput': '使用语音输入',
      'ai.voice.disableOutput': '关闭语音输出',
      'ai.voice.enableOutput': '开启语音输出',
      'ai.voice.speaking': '正在说话…',
      'ai.voice.tapInterrupt': '点击即可打断',
    'ai.voiceOnly.promptTap': '点击麦克风开始说话。帮助会直接语音回答。',
      'ai.voiceOnly.listening': '正在聆听…请开始说话。',
            'ai.voiceOnly.answeredOutLoud': '帮助已直接语音回答。如需再听一次，请重播语音回答。',
            'ai.voiceOnly.replay': '重播语音回答',
      'ai.voice.outputUnavailable': '语音输出不可用，请检查设备音量和音频权限。',
      'ai.voice.outputUnavailableWeb': '浏览器中的语音输出被阻止。请使用 HTTPS、允许自动播放/音频后再试。',
      'ai.clearGoals.title': '清除当前目标？',
      'ai.clearGoals.body': '这将移除此助理对话中的会话教练目标记忆。',
      'ai.clear': '清除',
      'ai.currentGoals': '当前目标',
      'ai.clearGoals.cta': '清除目标',
    'ai.empty.title': 'AI 帮助',
      'ai.empty.subtitle': '选择一种帮助方式并提出问题。我会引导你的思考，而不是直接给答案。',
      'ai.banner.verification': '理解检查已开启，请先展示你的思路。',
      'ai.banner.runtimeUnavailable':
          '实时学习信号当前不可用。在真实课堂证据到达前，置信度保持 0%，因此辅导会保持谨慎。',
      'ai.banner.runtimeMalformed': '实时学习信号当前不可信。在修复会话状态前，置信度保持 0%。',
      'ai.banner.learnerGuarded':
          '当前置信度为 {percent}%。帮助会结合实时学习信号与合成基线，并在低于 97% 时保持谨慎。',
      'ai.banner.lineageDisclosure':
          '帮助建议会结合实时学习信号与合成基线。合成基线只用于支持，不是学习者证据，也不是掌握证明。',
      'ai.chat.verificationRequired': '需要验证',
      'ai.chat.helpful': '有帮助吗？',
      'ai.feedback.thanks': '感谢你的反馈！',
      'ai.feedback.noted': '已记录，我们会继续改进。',
      'ai.enrich.retryPrompt': '我们再试一次。现在最让你困惑的部分是什么？',
      'ai.enrich.hintFollowup': '到目前为止你尝试了什么？',
      'ai.enrich.verifyFollowup': '你能展示支持你答案的证据吗？',
      'ai.enrich.explainFollowup': '你会如何用自己的话解释它？',
      'ai.enrich.debugFollowup': '问题出现之前刚刚发生了什么变化？',
      'ai.mode.hintPlaceholder': '请求一个提示…',
      'ai.mode.verifyPlaceholder': '描述你用于验证的方法…',
      'ai.mode.explainPlaceholder': '你希望解释什么？',
      'ai.mode.debugPlaceholder': '描述你当前看到的问题…',
      'ai.mode.hintLabel': '提示',
      'ai.mode.verifyLabel': '验证',
      'ai.mode.explainLabel': '解释',
      'ai.mode.debugLabel': '调试',
      'ai.directive.hint': '先给一个聚焦提示，再提出一个简短引导问题。',
      'ai.directive.verify': '用证据核验推理，并要求一个具体证明步骤。',
      'ai.directive.explain': '用简单步骤解释，并联系一个实际例子。',
      'ai.directive.debug': '诊断可能原因，建议一个小测试，并询问最近有什么变化。',
      'ai.role.learner': '请直接面向学习者，用支持性且符合年龄的教练语气回应。',
      'ai.role.parent': '请使用适合家长的表达方式，在不给答案的前提下支持学习者。',
      'ai.role.staff': '请以教学副驾驶的方式回应，给出简洁的教学建议。',
    },
    'zh-TW': <String, String>{
      'auth.welcomeBack': '歡迎回來',
      'auth.welcomeToScholesa': '歡迎來到 Scholesa',
      'auth.signInSubtitle': '登入以繼續你的學習旅程',
      'auth.email': '電子郵件',
      'auth.password': '密碼',
      'auth.emailHint': 'you@example.com',
      'auth.passwordHint': '••••••••',
      'auth.forgotPassword': '忘記密碼？',
      'auth.signIn': '登入',
      'auth.recentAccountsTitle': '這台裝置上的最近帳戶',
      'auth.recentAccountsSubtitle':
          '可使用已記住的家庭帳戶預填電子郵件，或繼續使用相同登入方式。系統不會儲存密碼，且同一時間只保留一個作用中的工作階段。',
      'auth.removeRememberedAccount': '移除',
      'auth.rememberedAccountRemoved': '該帳戶已從這台裝置移除。',
      'auth.useEmail': '使用電子郵件',
      'auth.savedAccount': '已儲存帳戶',
      'auth.orContinueWith': '或繼續使用',
      'auth.google': 'Google',
      'auth.microsoft': 'Microsoft',
      'auth.provisioningNote': '帳戶由站點或 HQ 管理員預先配置。',
      'auth.resetPassword': '重設密碼',
      'auth.resetPasswordHelp': '輸入你的電子郵件，我們會寄送重設密碼連結。',
      'auth.cancel': '取消',
      'auth.sendResetLink': '傳送重設連結',
      'auth.resetEmailSent': '密碼重設郵件已送出，請檢查收件匣。',
      'auth.validation.enterEmail': '請輸入電子郵件',
      'auth.validation.validEmail': '請輸入有效的電子郵件',
      'auth.validation.enterPassword': '請輸入密碼',
      'auth.validation.passwordLength': '密碼至少需要 6 個字元',
      'auth.error.userNotFound': '找不到此電子郵件對應的帳戶',
      'auth.error.wrongPassword': '密碼不正確',
      'auth.error.invalidCredential': '電子郵件或密碼無效',
      'auth.error.emailInUse': '此電子郵件已存在帳戶',
      'auth.error.weakPassword': '密碼強度不足',
      'auth.error.invalidEmail': '電子郵件格式無效',
      'auth.error.userDisabled': '此帳戶已停用',
      'auth.error.tooManyRequests': '嘗試次數過多，請稍後再試',
      'auth.error.networkFailed': '網路錯誤，請檢查連線後重試',
      'auth.error.operationNotAllowed': '目前未啟用電子郵件/密碼登入',
      'auth.error.invalidApiKey': '驗證設定有誤，請聯絡支援團隊',
      'auth.error.appNotAuthorized': '此應用程式未被授權使用 Firebase Auth',
      'auth.error.popupClosed': '登入彈窗在完成前已被關閉',
      'auth.error.popupBlocked': '登入彈窗被瀏覽器阻擋',
      'auth.error.googleFailed': '使用 Google 登入失敗',
      'auth.error.microsoftFailed': '使用 Microsoft 登入失敗',
      'auth.error.signOutFailed': '暫時無法登出，請再試一次。',
      'auth.error.profileLoadFailed': '載入使用者資料失敗',
      'auth.error.generic': '驗證失敗',
      'auth.error.unexpected': '發生未預期的錯誤',
      'auth.error.resetFailed': '傳送重設郵件失敗',
      'app.title': 'Scholesa',
      'app.bootstrapFailed': 'Scholesa 啟動失敗',
      'app.recoveryModeTitle': 'Scholesa 以復原模式啟動',
      'app.recoveryModeBody': '部分啟動服務失敗，因此在下次重新啟動前，應用的某些功能可能無法使用。',
      'app.affectedServices': '受影響的服務',
      'app.retry': '重試',
      'app.dismiss': '關閉',
      'app.startupService.localStorage': '本機儲存',
      'app.startupService.firebase': 'Firebase',
      'app.startupService.authEmulator': '認證模擬器',
      'app.startupService.generic': '啟動服務',
    'assistant.tooltip': '取得幫助',
    'assistant.title': '取得幫助',
      'assistant.close': '關閉',
    'assistant.loading': '正在載入幫助…',
    'assistant.hoverHint': '點擊取得幫助',
            'ai.greeting.initial': '你好！當你需要協助時，我可以提供提示、解釋和簡短除錯步驟。',
      'ai.autoAssist.hesitationPrompt':
          '學習者可能正在猶豫。當前支持狀態：{state}。請給出簡短支持性提醒、一個微小下一步以及一個追問。',
      'ai.autoAssist.interventionPrompt':
          '系統偵測到需要主動支持的時刻。介入類型：{type}，顯著性：{salience}，原因碼：{reasons}。請給出簡短支持性語音提醒，包含一個立即行動和一個追問。',
      'ai.autoAssist.fallbackPrompt': '請主動關心學習者，給出一個微小下一步，並提出一個建立信心的追問。',
    'ai.error.unreachable': '目前無法使用幫助，請稍後再試。',
      'ai.error.safeEscalation':
          '我想更謹慎一點。先告訴我你已經試過什麼，我可以幫你想下一步更安全的做法。如果你需要完整檢查，請請老師和你一起看。',
      'ai.voice.transcriptionUnavailable': '語音轉寫不可用，請改用文字輸入。',
      'ai.voice.microphonePermissionRequired': '語音輸入需要麥克風權限。',
      'ai.voice.playbackStopped': '播放已停止',
      'ai.voice.stopListening': '停止收聽',
      'ai.voice.useInput': '使用語音輸入',
      'ai.voice.disableOutput': '關閉語音輸出',
      'ai.voice.enableOutput': '開啟語音輸出',
      'ai.voice.speaking': '正在說話…',
      'ai.voice.tapInterrupt': '點擊即可打斷',
    'ai.voiceOnly.promptTap': '點擊麥克風開始說話。幫助會直接語音回答。',
      'ai.voiceOnly.listening': '正在聆聽…請開始說話。',
            'ai.voiceOnly.answeredOutLoud': '幫助已直接語音回答。如需再聽一次，請重播語音回答。',
            'ai.voiceOnly.replay': '重播語音回答',
      'ai.voice.outputUnavailable': '語音輸出不可用，請檢查裝置音量與音訊權限。',
      'ai.voice.outputUnavailableWeb': '瀏覽器中的語音輸出被阻擋。請使用 HTTPS、允許自動播放/音訊後再試。',
      'ai.clearGoals.title': '清除目前目標？',
      'ai.clearGoals.body': '這將移除此助理對話中的會話教練目標記憶。',
      'ai.clear': '清除',
      'ai.currentGoals': '目前目標',
      'ai.clearGoals.cta': '清除目標',
    'ai.empty.title': 'AI 幫助',
      'ai.empty.subtitle': '選擇一種幫助方式並提出問題。我會引導你的思考，而不是直接給答案。',
      'ai.banner.verification': '理解檢查已啟用，請先展示你的思路。',
      'ai.banner.runtimeUnavailable':
          '即時學習訊號目前不可用。在真實課堂證據到達前，信心維持 0%，因此輔導會保持謹慎。',
      'ai.banner.runtimeMalformed': '即時學習訊號目前不可信。在修復會話狀態前，信心維持 0%。',
      'ai.banner.learnerGuarded':
          '目前信心為 {percent}%。幫助會結合即時學習訊號與合成基線，並在低於 97% 時保持謹慎。',
      'ai.banner.lineageDisclosure':
          '幫助建議會結合即時學習訊號與合成基線。合成基線只用於支持，不是學習者證據，也不是掌握證明。',
      'ai.chat.verificationRequired': '需要驗證',
      'ai.chat.helpful': '有幫助嗎？',
      'ai.feedback.thanks': '感謝你的回饋！',
      'ai.feedback.noted': '已記錄，我們會持續改進。',
      'ai.enrich.retryPrompt': '我們再試一次。現在最讓你困惑的部分是什麼？',
      'ai.enrich.hintFollowup': '到目前為止你嘗試了什麼？',
      'ai.enrich.verifyFollowup': '你能展示支持你答案的證據嗎？',
      'ai.enrich.explainFollowup': '你會如何用自己的話解釋它？',
      'ai.enrich.debugFollowup': '問題出現之前剛剛發生了什麼變化？',
      'ai.mode.hintPlaceholder': '請求一個提示…',
      'ai.mode.verifyPlaceholder': '描述你用來驗證的方法…',
      'ai.mode.explainPlaceholder': '你希望解釋什麼？',
      'ai.mode.debugPlaceholder': '描述你目前看到的問題…',
      'ai.mode.hintLabel': '提示',
      'ai.mode.verifyLabel': '驗證',
      'ai.mode.explainLabel': '解釋',
      'ai.mode.debugLabel': '除錯',
      'ai.directive.hint': '先給一個聚焦提示，再提出一個簡短引導問題。',
      'ai.directive.verify': '用證據驗證推理，並要求一個具體證明步驟。',
      'ai.directive.explain': '用簡單步驟解釋，並連結一個實際例子。',
      'ai.directive.debug': '診斷可能原因，建議一個小測試，並詢問最近有什麼變化。',
      'ai.role.learner': '請直接面向學習者，以支持性且符合年齡的教練語氣回應。',
      'ai.role.parent': '請使用適合家長的表達方式，在不直接給答案的前提下支持學習者。',
      'ai.role.staff': '請以教學副駕的方式回應，提供簡潔的教學建議。',
    },
  };

  static String of(BuildContext context, String key) {
    final String localeCode = _canonicalLocale(Localizations.localeOf(context));
    final Map<String, String> selected =
        _localized[localeCode] ?? _localized['en']!;
    return selected[key] ?? _localized['en']![key] ?? key;
  }

  static String _canonicalLocale(Locale locale) {
    final String languageCode = locale.languageCode.toLowerCase();
    final String countryCode = (locale.countryCode ?? '').toUpperCase();
    if (languageCode == 'zh') {
      if (countryCode == 'TW' || countryCode == 'HK' || countryCode == 'MO') {
        return 'zh-TW';
      }
      return 'zh-CN';
    }
    return 'en';
  }
}
