import { getUatUser, type UatLoginRole, type UatUser } from '../fixtures/uat-seed-data';

export type MiloOSCoachMode = 'hint' | 'reflect' | 'analyze' | 'review';

export type MiloOSRequest = {
  learnerRole: UatLoginRole;
  educatorLed?: boolean;
  mode: MiloOSCoachMode;
  prompt: string;
  missionId: string;
  capabilityId: string;
  sessionId?: string;
  submissionId?: string;
};

export type MiloOSResponse = {
  allowed: boolean;
  refused: boolean;
  message: string;
  requiresEducator: boolean;
  auditEventId: string;
  capabilityId: string;
  supportType: 'policy-block' | 'guardrail-refusal' | 'scaffolded-support' | 'analytical-support' | 'advanced-critique';
  analyticalUseLabel?: string;
  disclosure: string;
};

export type MiloOSUsageLog = {
  id: string;
  learnerId: string;
  learnerEmail: string;
  tenantId: string;
  missionId: string;
  sessionId?: string;
  submissionId?: string;
  capabilityId: string;
  mode: MiloOSCoachMode;
  prompt: string;
  response: string;
  allowed: boolean;
  refused: boolean;
  educatorLed: boolean;
  policy: string | null;
  supportType: MiloOSResponse['supportType'];
  analyticalUseLabel?: string;
  createdAt: string;
};

export class MockMiloOSCoach {
  private readonly usageLogs: MiloOSUsageLog[] = [];

  async useCoach(request: MiloOSRequest): Promise<MiloOSResponse> {
    const learner = getUatUser(request.learnerRole);
    const requiresEducator = learner.aiPolicy === 'educator-led-only';
    const allowed = learner.role === 'learner' && (!requiresEducator || request.educatorLed === true);
    const refused = allowed && this.isNoCopyPrompt(request.prompt);
    const auditEventId = `ai-log-${this.usageLogs.length + 1}`;
    const supportType = this.supportTypeFor(learner, request, allowed, refused);
    const analyticalUseLabel = learner.aiPolicy === 'logged-analytical-use'
      ? 'logged analytical use'
      : undefined;
    const message = allowed && !refused
      ? this.createDeterministicResponse(learner, request)
      : refused
        ? 'I cannot complete learner work wholesale. I can offer questions, hints, structure, feedback, or examples while keeping learner ownership visible.'
      : 'MiloOS Coach is educator-led for this learner stage. Ask an Educator to facilitate the prompt.';

    this.usageLogs.push({
      id: auditEventId,
      learnerId: learner.id,
      learnerEmail: learner.email,
      tenantId: learner.tenantId,
      missionId: request.missionId,
      sessionId: request.sessionId,
      submissionId: request.submissionId,
      capabilityId: request.capabilityId,
      mode: request.mode,
      prompt: request.prompt,
      response: message,
      allowed,
      refused,
      educatorLed: request.educatorLed === true,
      policy: learner.aiPolicy ?? null,
      supportType,
      analyticalUseLabel,
      createdAt: new Date('2026-05-14T12:00:00.000Z').toISOString(),
    });

    return {
      allowed,
      refused,
      message,
      requiresEducator,
      auditEventId,
      capabilityId: request.capabilityId,
      supportType,
      analyticalUseLabel,
      disclosure: allowed
        ? 'MiloOS Coach response generated by deterministic UAT mock and recorded for audit.'
        : 'MiloOS Coach access denied by deterministic UAT learner AI policy.',
    };
  }

  linkUsageToSubmission(auditEventId: string, submissionId: string): void {
    const log = this.usageLogs.find((entry) => entry.id === auditEventId);

    if (!log) {
      throw new Error(`Unknown MiloOS usage log ${auditEventId}`);
    }

    log.submissionId = submissionId;
  }

  getUsageLogs(): MiloOSUsageLog[] {
    return [...this.usageLogs];
  }

  clear(): void {
    this.usageLogs.length = 0;
  }

  private createDeterministicResponse(learner: UatUser, request: MiloOSRequest): string {
    return [
      `Stage: ${learner.stage}.`,
      `Mode: ${request.mode}.`,
      'Next step: name the evidence, explain the prototype change, and connect it to the capability.',
    ].join(' ');
  }

  private isNoCopyPrompt(prompt: string): boolean {
    return [
      /write my full reflection/i,
      /give me the final answer/i,
      /do the whole project/i,
      /make it look like i wrote it/i,
      /create my complete pitch/i,
    ].some((pattern) => pattern.test(prompt));
  }

  private supportTypeFor(
    learner: UatUser,
    request: MiloOSRequest,
    allowed: boolean,
    refused: boolean
  ): MiloOSResponse['supportType'] {
    if (!allowed) {
      return 'policy-block';
    }

    if (refused) {
      return 'guardrail-refusal';
    }

    if (learner.aiPolicy === 'logged-analytical-use') {
      return 'analytical-support';
    }

    if (learner.aiPolicy === 'advanced-assistive-use-full-audit' || request.mode === 'review') {
      return 'advanced-critique';
    }

    return 'scaffolded-support';
  }
}
