import { getUatUser, type UatLoginRole, type UatUser } from '../fixtures/uat-seed-data';

export type MiloOSCoachMode = 'hint' | 'reflect' | 'analyze' | 'review';

export type MiloOSRequest = {
  learnerRole: UatLoginRole;
  educatorLed?: boolean;
  mode: MiloOSCoachMode;
  prompt: string;
  missionId: string;
  capabilityId: string;
};

export type MiloOSResponse = {
  allowed: boolean;
  message: string;
  requiresEducator: boolean;
  auditEventId: string;
  capabilityId: string;
  disclosure: string;
};

export type MiloOSUsageLog = {
  id: string;
  learnerId: string;
  learnerEmail: string;
  tenantId: string;
  missionId: string;
  capabilityId: string;
  mode: MiloOSCoachMode;
  prompt: string;
  response: string;
  allowed: boolean;
  educatorLed: boolean;
  policy: string | null;
  createdAt: string;
};

export class MockMiloOSCoach {
  private readonly usageLogs: MiloOSUsageLog[] = [];

  async useCoach(request: MiloOSRequest): Promise<MiloOSResponse> {
    const learner = getUatUser(request.learnerRole);
    const requiresEducator = learner.aiPolicy === 'educator-led-only';
    const allowed = learner.role === 'learner' && (!requiresEducator || request.educatorLed === true);
    const auditEventId = `ai-log-${this.usageLogs.length + 1}`;
    const message = allowed
      ? this.createDeterministicResponse(learner, request)
      : 'MiloOS Coach is educator-led for this learner stage. Ask an Educator to facilitate the prompt.';

    this.usageLogs.push({
      id: auditEventId,
      learnerId: learner.id,
      learnerEmail: learner.email,
      tenantId: learner.tenantId,
      missionId: request.missionId,
      capabilityId: request.capabilityId,
      mode: request.mode,
      prompt: request.prompt,
      response: message,
      allowed,
      educatorLed: request.educatorLed === true,
      policy: learner.aiPolicy ?? null,
      createdAt: new Date('2026-05-14T12:00:00.000Z').toISOString(),
    });

    return {
      allowed,
      message,
      requiresEducator,
      auditEventId,
      capabilityId: request.capabilityId,
      disclosure: allowed
        ? 'MiloOS Coach response generated by deterministic UAT mock and recorded for audit.'
        : 'MiloOS Coach access denied by deterministic UAT learner AI policy.',
    };
  }

  getUsageLogs(): MiloOSUsageLog[] {
    return [...this.usageLogs];
  }

  clear(): void {
    this.usageLogs.length = 0;
  }

  private createDeterministicResponse(learner: UatUser, request: MiloOSRequest): string {
    return [
      `Stage: ${learner.stage}.`,
      `Mode: ${request.mode}.`,
      'Next step: name the evidence, explain the prototype change, and connect it to the capability.',
    ].join(' ');
  }
}
